source 'https://rubygems.org'
gem "nokogiri", ">= 1.12.5"
gem 'rack', '~> 2.1.4'
gem 'rspec'
gem 'jekyll-theme-cayman'
gem "github-pages", "~> 215", group: :jekyll_plugins
gem "activesupport", ">= 6.0.3.1"
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem "kramdown", ">= 2.3.1"
